version: '3.8'

services:
  w8s:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: w8s-app
    ports:
      - "3000:80"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    networks:
      - w8s-network

networks:
  w8s-network:
    driver: bridge
